export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const GET_CART_ITEM = 'GET_CART_ITEM';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';
